CREATE USER testuser1 WITH PASSWORD '1234';

ALTER USER testuser1 WITH LOGIN;

GRANT CONNECT ON DATABASE sample TO testuser1;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO testuser1;

GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO testuser1;

